name: Update Blog Posts
on:
  schedule:
    - cron: '0 */6 * * *'  # 每6小时运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  update-posts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Update README
        uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://your-blog-feed-url.com/feed.xml"
          max_post_count: "5"
          readme_path: "README.md"
          template: "$newline* [$title]($url) - $date"
